v 0.1
askrynnikov/blackjack pull request #1
Opened 2016-12-01 19:58 UTC by askrynnikov

2016-12-02 16:32 UTC, psylone requested changes

2016-12-02 16:32 UTC, psylone commented on lib/deck.rb
> +class Deck
Поскольку здесь фактически колоды у нас нет, я бы назвал класс `AbstractDeck`.

2016-12-02 16:32 UTC, psylone commented on lib/desk/desk52.rb
> +  def shuffle!
Стоит вынести в базовый класс.

2016-12-02 16:32 UTC, psylone commented on lib/desk/desk52.rb
> +    if card.is_a?(Array)
Можно так: `@cards.push(*card)`. Один элемент добавится, а массив развернётся.

2016-12-02 16:32 UTC, psylone commented on lib/rules_blackjack.rb
> +    points = cards.reduce(0) { |acc, elem| acc + POINTS[elem.pip] }
Поскольку это карты, переменную в блоке стоит назвать `card`.

2016-12-02 16:32 UTC, psylone commented on main.rb
> +  compare = RulesBlackjack.comparison_points(player.points, dealer.points)
Если объяснишь почему у модуля возможно вызвать метод который не объявлен через `self`, я это зачту, хотя лучше так не делать поскольку ведёт к потенциальным ошибкам которые будет трудно отловить.

2016-12-02 16:32 UTC, psylone commented on lib/party.rb
> +class Party
Вероятно, это всё же `Player` или `User`.

2016-12-02 16:32 UTC, psylone commented on lib/party.rb
> +    return cards
`return` не нужен.

2016-12-02 16:32 UTC, psylone commented on main.rb
> +    puts "You have on the cards: #{player.show_cards}, points: #{player.points}"
Вывод меню лучше вынести в отдельный метод.

2016-12-02 16:32 UTC, psylone commented on main.rb
> +    break if choice == '3'
Это лучше сделать через `case`.

2016-12-03 01:33 UTC, askrynnikov commented on lib/deck.rb
> +class Deck
а как тогда назвать папку desk?

2016-12-03 02:35 UTC, askrynnikov commented on lib/rules_blackjack.rb
> +    points = cards.reduce(0) { |acc, elem| acc + POINTS[elem.pip] }
rubocop сказал именовать  |acc, elem| :)

2016-12-03 03:10 UTC, askrynnikov commented on main.rb
> +  compare = RulesBlackjack.comparison_points(player.points, dealer.points)
Метод экземпляра появляется как метод в классе, когда модуль подключен директивой include.
Я рассуждал что правила (как считать очки и определять победителя) должны знать все (игроки и сама игра)

2016-12-03 08:47 UTC, psylone commented on main.rb
> +  compare = RulesBlackjack.comparison_points(player.points, dealer.points)
С правилами понятно, тебя не смущает что метод после подключения модуля через `include` вызывается как статический метод у самого модуля?

2016-12-03 11:33 UTC, askrynnikov commented on main.rb
> +  compare = RulesBlackjack.comparison_points(player.points, dealer.points)
Упс! Да вместо `RulesBlackjack.comparison_points` пишем `comparison_points`

2016-12-04 16:11 UTC, psylone commented on lib/deck.rb
> +class Deck
Да, `deck` вполне подойдёт. Вот [здесь](https://github.com/rails/rails/tree/master/activerecord/lib/active_record/connection_adapters) хороший пример.

2016-12-04 16:12 UTC, psylone commented on lib/rules_blackjack.rb
> +    points = cards.reduce(0) { |acc, elem| acc + POINTS[elem.pip] }
Это да, но я за то чтобы проверять слова робота )

2016-12-04 16:22 UTC, psylone commented on main.rb
> +  compare = RulesBlackjack.comparison_points(player.points, dealer.points)
Да, именно так. Но я так задержал проверку потому что хотел тебе показать почему работают оба варианта.

Суть в том что глобальный контекст в котором мы работаем (если пишем в `irb` или в текстовом файле без классов) это объект класса `Object`. В этом легко убедиться если написать `p self.class`.

Но любой класс или модуль в Ruby тоже является объектом. Я называю их *объектами второго порядка*, хотя это не общепринятая терминология.

Таким образом, класс `Object` является объектом класса `Class`: `p Object.class`. Более того, каждый объект-модуль также является объектом, только уже не класса `Class`, а класса `Module`:  `p Kernel.class`.

Раз у нас есть классы `Class` и `Module` то возникает вопрос в какой иерархии наследования они находятся? Ситуация такая: `Class < Module < Object < BasicObject`.

Теперь когда мы делаем `include RulesBlackjack` мы на самом деле подключаем модуль в объект класса `Object`. Но поскольку класс `Module` наследует от `Object`, значит для объектов класса `Module` будут доступны методы пришедшие из того модуля который мы подключили в `Object`:

```ruby
# Сейчас мы находимся в глобальной области видимости, то есть внутри объекта
# класса `Object`
p self # => main
p self.class # => Object

include RulesBlackjack
# Теперь все методы в `RulesBlackjack` доступны для объектов класса `Module`

RulesBlackjack.comparison_points
# Это как раз работает потому что объект второго порядка `RulesBlackjack` является
# объектом класса `Module`
```

Всё бы ничего, но методы из `RulesBlackjack` также доступны и для объектов класса `Class`, например: `Fixnum.comparison_points`.

У Ruby довольно утончённая объектная модель если в неё погружаться, она позволяет многое но и аккуратности тоже требует )

2016-12-04 16:26 UTC, psylone approved these changes

2016-12-04 16:26 UTC, psylone commented on lib/deck.rb
> +  PIPS = { ace: 'A', two: '2', three: '3', four: '4', five: '5',
Кстати, если здесь у нас фактически абстрактный класс колоды, логичней эту константу перенести в дочерний класс.

2016-12-04 19:13 UTC, askrynnikov commented on main.rb
> +  compare = RulesBlackjack.comparison_points(player.points, dealer.points)
> Всё бы ничего, но методы из RulesBlackjack также доступны и для объектов класса Class, например: Fixnum.comparison_points.

Т.е. это единственная проблема?

Я правильно понимаю что она решается оберткой всего кода в class Main и def run, затем делаем run.rb и из него вызываем Main.run ? Так нужно было сделать?

2016-12-04 19:19 UTC, askrynnikov commented on lib/deck.rb
> +  PIPS = { ace: 'A', two: '2', three: '3', four: '4', five: '5',
Неа, лучше в конкретной колоде давать название карт.
По другому нужно было давать все! карты в абстрактной колоде, а здесь выбирать нужные хиртым образом, это запутывает.

2016-12-04 19:19 UTC, merged